name: CI with ImageMagick

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick libmagickwand-dev

    - name: Set up Ruby (if it's a Ruby project)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Specify your Ruby version
        bundler-cache: true # Runs bundle install and caches gems

    # Add your project-specific steps here
    # For example, for a Rails app:
    # - name: Setup Database (if needed)
    #   run: |
    #     cp config/database.yml.ci config/database.yml
    #     bundle exec rails db:create
    #     bundle exec rails db:schema:load

    - name: Run tests
      run: |
        # Replace with your actual test command
        # For a Rails app, it might be:
        # bundle exec rspec
        echo "Running tests..."
        # Example: Check ImageMagick version
        convert --version

    - name: Build project (if applicable)
      run: |
        # Replace with your actual build command
        echo "Building project..."
